/*
 * JS for Main generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'aa0880bc-f53f-47a7-8a6e-9f4385a7b3ac';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Main",
    "location": "Main.html"
}, {
    "name": "BankBalance",
    "location": "BankBalance.html"
}, {
    "name": "Results",
    "location": "Results.html"
}];

function Main_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilegrid_57': 'Main_mobilegrid_57',
        'mobilegridcell_58': 'Main_mobilegridcell_58',
        'mobiledatepicker_5': 'Main_mobiledatepicker_5',
        'mobilegridcell_68': 'Main_mobilegridcell_68',
        'mobilegridcell_110': 'Main_mobilegridcell_110',
        'mobilebutton_56': 'Main_mobilebutton_56',
        'mobilegrid_6': 'Main_mobilegrid_6',
        'mobilegridcell_7': 'Main_mobilegridcell_7',
        'mobilecheckboxgroup_39': 'Main_mobilecheckboxgroup_39',
        'mobilecheckbox_40': 'Main_mobilecheckbox_40',
        'mobilegridcell_8': 'Main_mobilegridcell_8',
        'mobiletextinput_17': 'Main_mobiletextinput_17',
        'mobilelabel_82': 'Main_mobilelabel_82',
        'mobiletextarea_83': 'Main_mobiletextarea_83',
        'mobiletoggle_119': 'Main_mobiletoggle_119',
        'mobilecheckboxgroup_152': 'Main_mobilecheckboxgroup_152',
        'mobilecheckbox_153': 'Main_mobilecheckbox_153',
        'mobilegrid_156': 'Main_mobilegrid_156',
        'mobilegridcell_157': 'Main_mobilegridcell_157',
        'mobilelabel_161': 'Main_mobilelabel_161',
        'mobilegridcell_158': 'Main_mobilegridcell_158',
        'mobileselectmenu_150': 'Main_mobileselectmenu_150',
        'mobileselectmenu_150-0': 'Main_mobileselectmenu_150-0',
        'mobilegrid_20': 'Main_mobilegrid_20',
        'mobilegridcell_21': 'Main_mobilegridcell_21',
        'mobilelabel_18': 'Main_mobilelabel_18',
        'mobilegridcell_22': 'Main_mobilegridcell_22',
        'mobilelabel_19': 'Main_mobilelabel_19',
        'mobilegridcell_74': 'Main_mobilegridcell_74',
        'mobilegridcell_111': 'Main_mobilegridcell_111',
        'mobilebutton_25': 'Main_mobilebutton_25',
        'mobilebutton_125': 'Main_mobilebutton_125',
        'CustomNavFooter_108': 'Main_CustomNavFooter_108',
        'CustomNavFooter_108_mobilenavbar_1': 'Main_CustomNavFooter_108_mobilenavbar_1',
        'CustomNavFooter_108_mobilenavbaritem_2': 'Main_CustomNavFooter_108_mobilenavbaritem_2',
        'CustomNavFooter_108_mobilenavbaritem_3': 'Main_CustomNavFooter_108_mobilenavbaritem_3',
        'CustomNavFooter_108_mobilenavbaritem_42': 'Main_CustomNavFooter_108_mobilenavbaritem_42',
        'mobilelabel_79': 'Main_mobilelabel_79',
        'mobilegrid_92': 'Main_mobilegrid_92',
        'mobilegridcell_93': 'Main_mobilegridcell_93',
        'mobilecheckboxgroup_64': 'Main_mobilecheckboxgroup_64',
        'mobilecheckbox_65': 'Main_mobilecheckbox_65',
        'mobilebutton_80': 'Main_mobilebutton_80',
        'html_164': 'Main_html_164',
        'mobilebutton_180': 'Main_mobilebutton_180',
        'html_168': 'Main_html_168',
        'mobilegrid_170': 'Main_mobilegrid_170',
        'mobilegridcell_171': 'Main_mobilegridcell_171',
        'mobilelabel_175': 'Main_mobilelabel_175',
        'mobilegridcell_172': 'Main_mobilegridcell_172',
        'userinput': 'Main_userinput',
        'mobilegridcell_173': 'Main_mobilegridcell_173',
        'mobilelabel_176': 'Main_mobilelabel_176',
        'mobilegridcell_174': 'Main_mobilegridcell_174',
        'passwordinput': 'Main_passwordinput',
        'mobilebutton_179': 'Main_mobilebutton_179'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["Main_mobileselectmenu_150_onchange_mapping_0"] = {
        "homeScreen": "Main",
        "directions": [

        {
            "from_name": "Main",
            "from_type": "UI",

            "to_name": "hostPlayer",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['mobileselectmenu_150:selectedMenuItem']",
                "target": "$"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["Main_playersService_onbeforesend_mapping_0"] = {
        "homeScreen": "Main",
        "directions": [

        {
            "from_name": "userSessionToken",
            "from_type": "LOCAL_STORAGE",

            "to_name": "playersService",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['headers']['Authorization']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["Main_playersService_onsuccess_mapping_0"] = {
        "homeScreen": "Main",
        "directions": [

        {
            "from_name": "playersService",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "Main",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body'][i]['Name']",
                "target": "$['mobilegrid_6']['mobilecheckbox_40:text']"

            },

            {

                "source": "$['body'][i]['Name']",
                "target": "$['mobilecheckbox_65:text']"

            },

            {

                "source": "$['body'][i]",
                "target": "$['mobilegrid_6']"

            },

            {

                "source": "$['body'][i]",
                "target": "$['mobilecheckbox_65']"

            },

            {

                "source": "$['body'][i]['Frequent']",
                "target_transformation": function(value, element) {
                    return !value;
                },
                "target": "$['mobilecheckbox_65:visible']"

            },

            {

                "source": "$['body'][i]['Frequent']",
                "target": "$['mobilegrid_6']['mobilecheckbox_40:checkboxSelected']"

            },

            {

                "source": "$['body'][i]['Frequent']",
                "target": "$['mobilegrid_6']['mobilecheckboxgroup_39:visible']"

            },

            {

                "source": "$['body'][i]['Frequent']",
                "target": "$['mobilegrid_6']['mobiletextinput_17:visible']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["Main_GamesResults_create_service_onbeforesend_mapping_0"] = {
        "homeScreen": "Main",
        "directions": [

        {
            "from_name": "gameResults",
            "from_type": "LOCAL_STORAGE",

            "to_name": "GamesResults_create_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": {
                    "acl": {
                        "*": {
                            "write": true,
                            "read": true
                        }
                    }
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['results_string']"

            }

            ]
        },

        {
            "from_name": "checksum",
            "from_type": "LOCAL_STORAGE",

            "to_name": "GamesResults_create_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": {
                    "acl": {
                        "*": {
                            "write": true,
                            "read": true
                        }
                    }
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['checksum']"

            }

            ]
        },

        {
            "from_name": "gameDate",
            "from_type": "LOCAL_STORAGE",

            "to_name": "GamesResults_create_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": {
                    "acl": {
                        "*": {
                            "write": true,
                            "read": true
                        }
                    }
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['date_string']"

            }

            ]
        },

        {
            "from_name": "comments",
            "from_type": "LOCAL_STORAGE",

            "to_name": "GamesResults_create_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": {
                    "acl": {
                        "*": {
                            "write": true,
                            "read": true
                        }
                    }
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['comments']"

            }

            ]
        },

        {
            "from_name": "userSessionToken",
            "from_type": "LOCAL_STORAGE",

            "to_name": "GamesResults_create_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": {
                    "acl": {
                        "*": {
                            "write": true,
                            "read": true
                        }
                    }
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['headers']['Authorization']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["Main_updatePlayersStats_onbeforesend_mapping_0"] = {
        "homeScreen": "Main",
        "directions": [

        {
            "from_name": "userSessionToken",
            "from_type": "LOCAL_STORAGE",

            "to_name": "updatePlayersStats",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "Content-Type": "text/plain"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['headers']['Authorization']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["Main_updatePlayersStats_onsuccess_mapping_0"] = {
        "homeScreen": "Main",
        "directions": []
    };

    Apperyio.mappings["Main_MailService_onbeforesend_mapping_0"] = {
        "homeScreen": "Main",
        "directions": [

        {
            "from_name": "gameDate",
            "from_type": "LOCAL_STORAGE",

            "to_name": "MailService",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target_transformation": function(value) {
                    return "Poker results " + value;
                },
                "target": "$['parameters']['subject']"

            }

            ]
        },

        {
            "from_name": "gameResults",
            "from_type": "LOCAL_STORAGE",

            "to_name": "MailService",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target_transformation": function(value) {
                    //str = value.replace(/:/g,"</td><td>");
                    //str = str.replace(/,/g,"</td></tr><tr><td>");
                    //return "<table><tr><td>" + str + "</td></tr></table>";
                    str = value.replace(/,/g, "\n");
                    return str;
                },
                "target": "$['parameters']['body']"

            },

            {

                "source": "$",
                "target_transformation": function(value) {
                    str = value.replace(/,/g, "\n");
                    return str;
                },
                "target": "$['parameters']['results']"

            }

            ]
        },

        {
            "from_name": "comments",
            "from_type": "LOCAL_STORAGE",

            "to_name": "MailService",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['comments']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["Main_MailService_onsuccess_mapping_0"] = {
        "homeScreen": "Main",
        "directions": []
    };

    Apperyio.mappings["Main_Transactions_create_service_onbeforesend_mapping_0"] = {
        "homeScreen": "Main",
        "directions": [

        {
            "from_name": "gameResults",
            "from_type": "LOCAL_STORAGE",

            "to_name": "Transactions_create_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": {
                    "type": "Game",
                    "acl": {
                        "*": {
                            "write": true,
                            "read": true
                        }
                    }
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['transaction_string']"

            }

            ]
        },

        {
            "from_name": "checksum",
            "from_type": "LOCAL_STORAGE",

            "to_name": "Transactions_create_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": {
                    "type": "Game",
                    "acl": {
                        "*": {
                            "write": true,
                            "read": true
                        }
                    }
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['checksum']"

            }

            ]
        },

        {
            "from_name": "gameDate",
            "from_type": "LOCAL_STORAGE",

            "to_name": "Transactions_create_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": {
                    "type": "Game",
                    "acl": {
                        "*": {
                            "write": true,
                            "read": true
                        }
                    }
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['date_string']"

            }

            ]
        },

        {
            "from_name": "comments",
            "from_type": "LOCAL_STORAGE",

            "to_name": "Transactions_create_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": {
                    "type": "Game",
                    "acl": {
                        "*": {
                            "write": true,
                            "read": true
                        }
                    }
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['comments']"

            }

            ]
        },

        {
            "from_name": "transactionType",
            "from_type": "LOCAL_STORAGE",

            "to_name": "Transactions_create_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": {
                    "type": "Game",
                    "acl": {
                        "*": {
                            "write": true,
                            "read": true
                        }
                    }
                }
            },

            "mappings": [

            {

                "source": "$",
                "target_transformation": function(value) {
                    return "game";
                },
                "target": "$['body']['type']"

            }

            ]
        },

        {
            "from_name": "userSessionToken",
            "from_type": "LOCAL_STORAGE",

            "to_name": "Transactions_create_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": {
                    "type": "Game",
                    "acl": {
                        "*": {
                            "write": true,
                            "read": true
                        }
                    }
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['headers']['Authorization']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["Main_Transactions_create_service_onsuccess_mapping_0"] = {
        "homeScreen": "Main",
        "directions": []
    };

    Apperyio.mappings["Main_updateBankBalance_onbeforesend_mapping_0"] = {
        "homeScreen": "Main",
        "directions": [

        {
            "from_name": "userSessionToken",
            "from_type": "LOCAL_STORAGE",

            "to_name": "updateBankBalance",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['headers']['Authorization']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["Main_updateBankBalance_onsuccess_mapping_0"] = {
        "homeScreen": "Main",
        "directions": []
    };

    Apperyio.mappings["Main_updateBankBalance_withNavigateToBankPage_onbeforesend_mapping_0"] = {
        "homeScreen": "Main",
        "directions": [

        {
            "from_name": "userSessionToken",
            "from_type": "LOCAL_STORAGE",

            "to_name": "updateBankBalance_withNavigateToBankPage",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['headers']['Authorization']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["Main_updateBankBalance_withNavigateToBankPage_onsuccess_mapping_0"] = {
        "homeScreen": "Main",
        "directions": []
    };

    Apperyio.mappings["Main_Transactions_create_service_withNavigateToBankPage_onbeforesend_mapping_0"] = {
        "homeScreen": "Main",
        "directions": [

        {
            "from_name": "gameResults",
            "from_type": "LOCAL_STORAGE",

            "to_name": "Transactions_create_service_withNavigateToBankPage",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": {
                    "type": "Game",
                    "acl": {
                        "*": {
                            "write": true,
                            "read": true
                        }
                    }
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['transaction_string']"

            }

            ]
        },

        {
            "from_name": "checksum",
            "from_type": "LOCAL_STORAGE",

            "to_name": "Transactions_create_service_withNavigateToBankPage",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": {
                    "type": "Game",
                    "acl": {
                        "*": {
                            "write": true,
                            "read": true
                        }
                    }
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['checksum']"

            }

            ]
        },

        {
            "from_name": "comments",
            "from_type": "LOCAL_STORAGE",

            "to_name": "Transactions_create_service_withNavigateToBankPage",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": {
                    "type": "Game",
                    "acl": {
                        "*": {
                            "write": true,
                            "read": true
                        }
                    }
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['comments']"

            }

            ]
        },

        {
            "from_name": "gameDate",
            "from_type": "LOCAL_STORAGE",

            "to_name": "Transactions_create_service_withNavigateToBankPage",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": {
                    "type": "Game",
                    "acl": {
                        "*": {
                            "write": true,
                            "read": true
                        }
                    }
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['date_string']"

            }

            ]
        },

        {
            "from_name": "transactionType",
            "from_type": "LOCAL_STORAGE",

            "to_name": "Transactions_create_service_withNavigateToBankPage",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": {
                    "type": "Game",
                    "acl": {
                        "*": {
                            "write": true,
                            "read": true
                        }
                    }
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['type']"

            }

            ]
        },

        {
            "from_name": "userSessionToken",
            "from_type": "LOCAL_STORAGE",

            "to_name": "Transactions_create_service_withNavigateToBankPage",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": {
                    "type": "Game",
                    "acl": {
                        "*": {
                            "write": true,
                            "read": true
                        }
                    }
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['headers']['Authorization']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["Main_Transactions_create_service_withNavigateToBankPage_onsuccess_mapping_0"] = {
        "homeScreen": "Main",
        "directions": []
    };

    Apperyio.mappings["Main_Transactions_create_Host_service_onbeforesend_mapping_0"] = {
        "homeScreen": "Main",
        "directions": [

        {
            "from_name": "hostTransaction",
            "from_type": "LOCAL_STORAGE",

            "to_name": "Transactions_create_Host_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": {
                    "type": "Game",
                    "acl": {
                        "*": {
                            "write": true,
                            "read": true
                        }
                    }
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['transaction_string']"

            }

            ]
        },

        {
            "from_name": "gameDate",
            "from_type": "LOCAL_STORAGE",

            "to_name": "Transactions_create_Host_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": {
                    "type": "Game",
                    "acl": {
                        "*": {
                            "write": true,
                            "read": true
                        }
                    }
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['date_string']"

            }

            ]
        },

        {
            "from_name": "transactionType",
            "from_type": "LOCAL_STORAGE",

            "to_name": "Transactions_create_Host_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": {
                    "type": "Game",
                    "acl": {
                        "*": {
                            "write": true,
                            "read": true
                        }
                    }
                }
            },

            "mappings": [

            {

                "source": "$",
                "target_transformation": function(value) {
                    return "host";
                },
                "target": "$['body']['type']"

            }

            ]
        },

        {
            "from_name": "hostComments",
            "from_type": "LOCAL_STORAGE",

            "to_name": "Transactions_create_Host_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": {
                    "type": "Game",
                    "acl": {
                        "*": {
                            "write": true,
                            "read": true
                        }
                    }
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['comments']"

            }

            ]
        },

        {
            "from_name": "checksum",
            "from_type": "LOCAL_STORAGE",

            "to_name": "Transactions_create_Host_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": {
                    "type": "Game",
                    "acl": {
                        "*": {
                            "write": true,
                            "read": true
                        }
                    }
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['checksum']"

            }

            ]
        },

        {
            "from_name": "userSessionToken",
            "from_type": "LOCAL_STORAGE",

            "to_name": "Transactions_create_Host_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": {
                    "type": "Game",
                    "acl": {
                        "*": {
                            "write": true,
                            "read": true
                        }
                    }
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['headers']['Authorization']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["Main_basic_login_service_onbeforesend_mapping_0"] = {
        "homeScreen": "Main",
        "directions": [
            {
                "from_name": "userSessionToken",
                "from_type": "LOCAL_STORAGE",

                "to_name": "basic_login_service",
                "to_type": "SERVICE_REQUEST",

                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "Content-Type": "application/json"
                    },
                    "parameters": {},
                    "body": {
                        "type": "Game",
                        "acl": {
                            "*": {
                                "write": true,
                                "read": true
                            }
                        }
                    }
                },

                "mappings": [

                {

                    "source": "$",
                    "target": "$['headers']['Authorization']"

                }

                ]
            }

        /*,
        {
            "from_name": "user",
            "from_type": "LOCAL_STORAGE",

            "to_name": "basic_login_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['username']"

            }

            ]
        },

        {
            "from_name": "password",
            "from_type": "LOCAL_STORAGE",

            "to_name": "basic_login_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['password']"

            }

            ]
        }*/

        ]
    };
   /*
    Apperyio.mappings["Main_basic_login_service_onsuccess_mapping_0"] = {
        "homeScreen": "Main",
        "directions": [

        {
            "from_name": "basic_login_service",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "userSessionToken",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['body']['sessionToken']",
                "target": "$"

            }

            ]
        }

        ]
    };*/

    Apperyio.datasources = Apperyio.datasources || {};

    window.playersService = Apperyio.datasources.playersService = new Apperyio.DataSource(pkrDB_Players_list_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Main_playersService_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Main_playersService_onsuccess_mapping_0"]);
            onPlayersLoaded();
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            try {
                basic_login_service.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
        }
    });

    window.GamesResults_create_service = Apperyio.datasources.GamesResults_create_service = new Apperyio.DataSource(pkrDB_GamesResults_create_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Main_GamesResults_create_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            try {
              copyResultsToClipboard();
            } catch (e) {
                console.error(e);
            };
            try {
                
                updatePlayersStats.execute({
                    success: function( e ) {
                        //Success handler here
                        Apperyio.navigateTo('Results', {
                            reverse: false
                        });
                    }
                });
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
            try {
                Transactions_create_service.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
            try {
                Transactions_create_Host_service.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
            try {
                MailService.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };

        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.updatePlayersStats = Apperyio.datasources.updatePlayersStats = new Apperyio.DataSource(updatePlayersStats_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Main_updatePlayersStats_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Main_updatePlayersStats_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.MailService = Apperyio.datasources.MailService = new Apperyio.DataSource(RESTMailService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Main_MailService_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Main_MailService_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.Transactions_create_service = Apperyio.datasources.Transactions_create_service = new Apperyio.DataSource(pkrDB_Transactions_create_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Main_Transactions_create_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Main_Transactions_create_service_onsuccess_mapping_0"]);
            try {
                updateBankBalance.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.updateBankBalance = Apperyio.datasources.updateBankBalance = new Apperyio.DataSource(updateBankBalance_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Main_updateBankBalance_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Main_updateBankBalance_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.updateBankBalance_withNavigateToBankPage = Apperyio.datasources.updateBankBalance_withNavigateToBankPage = new Apperyio.DataSource(updateBankBalance_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Main_updateBankBalance_withNavigateToBankPage_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Main_updateBankBalance_withNavigateToBankPage_onsuccess_mapping_0"]);
            Apperyio.navigateTo('BankBalance', {
                reverse: false
            });
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.Transactions_create_service_withNavigateToBankPage = Apperyio.datasources.Transactions_create_service_withNavigateToBankPage = new Apperyio.DataSource(pkrDB_Transactions_create_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Main_Transactions_create_service_withNavigateToBankPage_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Main_Transactions_create_service_withNavigateToBankPage_onsuccess_mapping_0"]);
            try {
                updateBankBalance_withNavigateToBankPage.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.Transactions_create_Host_service = Apperyio.datasources.Transactions_create_Host_service = new Apperyio.DataSource(pkrDB_Transactions_create_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Main_Transactions_create_Host_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
          try {
              updateBankBalance.execute({});
          } catch (e) {
              console.error(e);
              hideSpinner();
          };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.basic_login_service = Apperyio.datasources.basic_login_service = new Apperyio.DataSource(pkrDB_login_service, {
        "onBeforeSend": function(jqXHR) {
            var user = localStorage.getItem('user');
            var password = localStorage.getItem('password');
            var base64 = btoa(user+':'+password);
       var basicAuth = "Basic " + base64;
       localStorage.setItem('userSessionToken', basicAuth);
       Apperyio.processMappingAction(Apperyio.mappings["Main_basic_login_service_onbeforesend_mapping_0"]);

        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
           // Apperyio.processMappingAction(Apperyio.mappings["Main_basic_login_service_onsuccess_mapping_0"]);
            Apperyio('basicloginpopup').popup('close');
            try {
                playersService.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            console.log(jqXHR);
            console.log(errorThrown);
            console.log(this);;
            var popupElement = Apperyio("basicloginpopup");
            if (popupElement.popup("option", "positionTo") === "origin") {
                popupElement.popup("open", {
                    transition: "none",
                    positionTo: "#" + $(this).attr("id")
                });
            } else {
                popupElement.popup("open", {
                    transition: "none"
                });
            };
        }

    });

    Apperyio.CurrentScreen = 'Main';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var Main_onLoad = function() {
            Main_elementsExtraJS();

            onLoad();

            Main_deviceEvents();
            Main_windowEvents();
            Main_elementsEvents();
        };

    // screen window events


    function Main_windowEvents() {

        $('#Main').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        $('#Main').on({
            pageshow: function(event) {
                try {
                    playersService.execute({});
                } catch (e) {
                    console.error(e);
                    hideSpinner();
                };
            },
        });

    };

    // device events


    function Main_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function Main_elementsExtraJS() {
        // screen (Main) extra code

        /* mobiledatepicker_5 */

        Main_mobiledatepicker_5_selector = "#Main_mobiledatepicker_5";
        Main_mobiledatepicker_5_dataPickerOptions = {
            dateFormat: "dd/mm/yy",
            firstDay: 0,

            maxDate: new Date(""),

            minDate: new Date(""),

            dayNamesMin: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
            monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
            showOtherMonths: true
        };

        Main_mobiledatepicker_5_dataPickerOptions.defaultDate = new Date("01/01/2015");

        Apperyio.__registerComponent('mobiledatepicker_5', new Apperyio.ApperyMobileDatePickerComponent("Main_mobiledatepicker_5", Main_mobiledatepicker_5_dataPickerOptions));

        /* mobiletoggle_119 */

        $("#Main_mobiletoggle_119").parent().find(".ui-flipswitch-on").attr("tabindex", "17");

        /* mobileselectmenu_150 */

        $("#Main_mobileselectmenu_150").parent().find("a.ui-btn").attr("tabindex", "28");

        /* mobilepopup_167 */
        $("#Main_mobilepopup_167").popup("option", "positionTo", "window");

        /* basicloginpopup */
        $("#Main_basicloginpopup").popup("option", "positionTo", "window");

    };

    // screen elements handler


    function Main_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("change", '#Main_mobilecontainer [name="mobiledatepicker_5"]').on({
            change: function(event) {
                try {
                    $a.storage["gameDate"].update("$", $a.c15r($a.UIHandler.resolveGeneratedComponent('mobiledatepicker_5', this), 'get', 'defaultDateValue'))
                } catch (e) {
                    console.error(e)
                };
            },
        }, '#Main_mobilecontainer [name="mobiledatepicker_5"]');

        $(document).off("click", '#Main_mobilecontainer [name="mobilebutton_56"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    $('[id="Main_panel_47"]').panel("open");

                }
            },
        }, '#Main_mobilecontainer [name="mobilebutton_56"]');

        $(document).off("change", '#Main_mobilecontainer [name="mobilecheckbox_40"]').on({
            change: function(event) {
                onValueChanged();
            },
        }, '#Main_mobilecontainer [name="mobilecheckbox_40"]');

        $(document).off("input", '#Main_mobilecontainer [name="mobiletextinput_17"]').on({
            input: function(event) {
                onValueChanged();
            },
        }, '#Main_mobilecontainer [name="mobiletextinput_17"]');

        $(document).off("change", '#Main_mobilecontainer [name="mobiletextarea_83"]').on({
            change: function(event) {
                try {
                    $a.storage["comments"].update("$", $a.c15r($a.UIHandler.resolveGeneratedComponent('mobiletextarea_83', this), 'get', 'text'))
                } catch (e) {
                    console.error(e)
                };
            },
        }, '#Main_mobilecontainer [name="mobiletextarea_83"]');
        $(document).off("change", '#Main_mobilecontainer [name="mobiletoggle_119"]').on({
            change: function(event) {
                try {
                    $a.storage["gameFlag"].update("$", "")
                } catch (e) {
                    console.error(e)
                };
                toggle('Main_mobilebutton_25', 'mob', $a.storage["gameFlag"].get("$"));
                toggle('Main_mobilebutton_125', 'mob', $a.storage["gameFlag"].get("$"));
                toggle('Main_mobilecheckbox_153', 'mob', $a.storage["gameFlag"].get("$"));
                toggle('Main_mobileselectmenu_150', 'mob', $a.storage["gameFlag"].get("$"));
                toggle('Main_mobilelabel_161', 'mob', $a.storage["gameFlag"].get("$"));
            },
        }, '#Main_mobilecontainer [name="mobiletoggle_119"]');

        $(document).off("click", '#Main_mobilecontainer [name="mobilecheckbox_153"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    onPizzaClick();

                }
            },
        }, '#Main_mobilecontainer [name="mobilecheckbox_153"]');

        $(document).off("change", '#Main_mobilecontainer [name="mobileselectmenu_150"]').on({
            change: function(event) {
                Apperyio.processMappingAction(Apperyio.mappings["Main_mobileselectmenu_150_onchange_mapping_0"]);
                onHostChanged();
            },
        }, '#Main_mobilecontainer [name="mobileselectmenu_150"]');

        $(document).off("click focus", '#Main_mobilefooter [name="mobilebutton_25"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        GamesResults_create_service.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
            focus: function(event) {
                if ($("[name=mobilebutton_25]").attr("disabled") == "disabled") alert("No players selected or checksum is not 0");
            },
        }, '#Main_mobilefooter [name="mobilebutton_25"]');
        $(document).off("click focus", '#Main_mobilefooter [name="mobilebutton_125"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    var isPizza = $("[name=mobilecheckbox_153]").find("input").is(':checked');

                    if (isPizza) localStorage.setItem('transactionType', 'pizza');
                    else localStorage.setItem('transactionType', 'bank');

                    ;
                    try {
                        Transactions_create_service_withNavigateToBankPage.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
            focus: function(event) {
                if ($("[name=mobilebutton_25]").attr("disabled") === "disabled" || $("[name=mobilebutton_125]").attr("disabled") === "disabled") alert("No players selected or checksum is not 0");
            },
        }, '#Main_mobilefooter [name="mobilebutton_125"]');

        $(document).off("click", '#Main_mobilefooter [name="CustomNavFooter_108_mobilenavbaritem_2"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Main', {
                        reverse: false
                    });

                }
            },
        }, '#Main_mobilefooter [name="CustomNavFooter_108_mobilenavbaritem_2"]');
        $(document).off("click", '#Main_mobilefooter [name="CustomNavFooter_108_mobilenavbaritem_3"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Results', {
                        reverse: false
                    });

                }
            },
        }, '#Main_mobilefooter [name="CustomNavFooter_108_mobilenavbaritem_3"]');
        $(document).off("click", '#Main_mobilefooter [name="CustomNavFooter_108_mobilenavbaritem_42"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('BankBalance', {
                        reverse: false
                    });

                }
            },
        }, '#Main_mobilefooter [name="CustomNavFooter_108_mobilenavbaritem_42"]');

        $(document).off("change", '#Main_panel_47 [name="mobilecheckbox_65"]').on({
            change: function(event) {
                addPlayers();
            },
        }, '#Main_panel_47 [name="mobilecheckbox_65"]');
        $(document).off("click", '#Main_panel_47 [name="mobilebutton_80"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    $('[id="Main_panel_47"]').panel("close");

                }
            },
        }, '#Main_panel_47 [name="mobilebutton_80"]');

        $('#Main_panel_163').off("panelopen").on("panelopen", function(event) {
            var popupElement = Apperyio("basicloginpopup");
            if (popupElement.popup("option", "positionTo") === "origin") {
                popupElement.popup("open", {
                    transition: "fade",
                    positionTo: "#" + $(this).attr("id")
                });
            } else {
                popupElement.popup("open", {
                    transition: "fade"
                });
            };
            $('[id="Main_panel_163"]').panel("close");
        });

        $(document).off("change", '#Main_basicloginpopup [name="userinput"]').on({
            change: function(event) {
                try {
                    $a.storage["user"].update("$", $a.c15r($a.UIHandler.resolveGeneratedComponent('userinput', this), 'get', 'text'))
                } catch (e) {
                    console.error(e)
                };
            },
        }, '#Main_basicloginpopup [name="userinput"]');

        $(document).off("change", '#Main_basicloginpopup [name="passwordinput"]').on({
            change: function(event) {
                try {
                    $a.storage["password"].update("$", $a.c15r($a.UIHandler.resolveGeneratedComponent('passwordinput', this), 'get', 'text'))
                } catch (e) {
                    console.error(e)
                };
            },
        }, '#Main_basicloginpopup [name="passwordinput"]');
        $(document).off("click", '#Main_basicloginpopup [name="mobilebutton_179"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        basic_login_service.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#Main_basicloginpopup [name="mobilebutton_179"]');

    };

    $(document).off("pagebeforeshow", "#Main").on("pagebeforeshow", "#Main", function(event, ui) {
        Apperyio.CurrentScreen = "Main";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    Main_onLoad();
};

$(document).off("pagecreate", "#Main").on("pagecreate", "#Main", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Main_js();
});
